### ISSUE TITLE
Empty keys reported as errors sometimes

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#45] opened 2019-12-11 12:15 UTC
`{"":"0Ý"}`: Failed to find all structural indices for stage 1,
`{"":{"":{"":null}}}`: Bad parsing while executing stage 2
`{"":60000000000000000000}`: No error?

`json.Unmarshal` accepts empty keys.

**Comment by fwessels** [comment] 2019-12-13 22:16
First two pass successfully, last one is a duplicate of #47

**Closed as completed by fwessels** 2019-12-13 22:16 UTC
