### ISSUE TITLE
panic: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#38] opened 2019-12-06 14:04 UTC
```
goroutine 8 [running]:
sync.(*WaitGroup).Add(0xc0000120f0, 0xffffffffffffffff)
	sync/waitgroup.go:74 +0x140
sync.(*WaitGroup).Done(...)
	sync/waitgroup.go:99
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage.func2(0xc0000120e0, 0xc, 0x10, 0xc0000d2000, 0xc000046040, 0xc0000120f0)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:110 +0xbb
created by github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:106 +0x1a2

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0000120f8)
	runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc0000120f0)
	sync/waitgroup.go:130 +0x6b
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage(0xc0000d2000, 0xc0000120e0, 0xc, 0x10, 0x1, 0x1)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:113 +0x1c6
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessageNdjson(0xc0000d2000, 0x3db0000, 0xc, 0xc, 0xc, 0xc)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:124 +0xfb
github.com/fwessels/simdjson-go.ParseND(0x3db0000, 0xc, 0xc, 0x0, 0x1, 0x69, 0x0)
	c:/gopath/src/github.com/fwessels/simdjson-go/simdjson.go:60 +0x1b4
github.com/klauspost/simdjson-fuzz.Fuzz(0x3db0000, 0xc, 0xc, 0x624)
	c:/gopath/src/github.com/klauspost/simdjson-fuzz/json.go:65 +0x5e8
go-fuzz-dep.Main(0xc0000abf48, 0x1, 0x1)
	go-fuzz-dep/main.go:36 +0x1b4
main.main()
	github.com/klauspost/simdjson-fuzz/go.fuzz.main/main.go:15 +0x59
exit status 2
```

Input: `{"":"\u000"}`

**Comment by fwessels** [comment] 2019-12-06 17:40
Duplicate of #33

**Closed as completed by fwessels** 2019-12-06 17:40 UTC
