### ISSUE TITLE
parse_number_simd: index out of range [1] with length 1

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#43] opened 2019-12-11 11:32 UTC
```
panic: runtime error: index out of range [1] with length 1

goroutine 389 [running]:
github.com/fwessels/simdjson-go.parse_number_simd(0x3e328c3, 0x1, 0x1, 0x101, 0xc000040101, 0x40f5952d57e1809f, 0x0)
	c:/gopath/src/github.com/fwessels/simdjson-go/parse_number_amd64.go:28 +0x45e
github.com/fwessels/simdjson-go.parse_number(0x3e30000, 0x28c4, 0x28c4, 0xc0002ae000, 0x28c3, 0xc000049f01, 0x0)
	c:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:35 +0x98
github.com/fwessels/simdjson-go.unified_machine(0x3e30000, 0x28c4, 0x28c4, 0xc0002ae000, 0x587ef8)
	c:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:309 +0xe1f
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage.func2(0x3e30000, 0x28c4, 0x28c4, 0xc0002ae000, 0xc0000468e0, 0xc0000126d0)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:107 +0x6c
created by github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:106 +0x1a2

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0000126d8)
	runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc0000126d0)
	sync/waitgroup.go:130 +0x6b
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage(0xc0002ae000, 0x3e30000, 0x28c4, 0x28c4, 0xc00004bcb0, 0x457590)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:116 +0x1c8
github.com/fwessels/simdjson-go.Parse(0x3e30000, 0x28c4, 0x28c4, 0x0, 0xc00004bf90, 0x4647a2, 0x684ea0)
	c:/gopath/src/github.com/fwessels/simdjson-go/simdjson.go:36 +0x22b
github.com/klauspost/simdjson-fuzz.Fuzz(0x3e30000, 0x28c4, 0x28c4, 0x3)
	c:/gopath/src/github.com/klauspost/simdjson-fuzz/json.go:16 +0xbf
go-fuzz-dep.Main(0xc00004bf40, 0x2, 0x2)
	go-fuzz-dep/main.go:36 +0x1b4
main.main()
	github.com/klauspost/simdjson-fuzz/go.fuzz.main/main.go:17 +0x64
exit status 2
```

Repro: [73cff18b89617d0f6765d9d89ea527fdce4f47be.gz](https://github.com/fwessels/simdjson-go/files/3950096/73cff18b89617d0f6765d9d89ea527fdce4f47be.gz)

**Comment by fwessels** [comment] 2019-12-13 21:26
Duplicate of #44

**Closed as completed by fwessels** 2019-12-13 21:26 UTC
