### ISSUE TITLE
Bool array parsing.

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#48] opened 2019-12-12 09:23 UTC
Sending as content for TestParsePassCases:
```
		{
			name:    "bad-bool-array",
			js:      `{"0":[true,true,true,true]}`,
			want:    `{"0":[true,true,true,true]}`,
			wantErr: false,
		},
```
Got: ` TestParsePassCases() error = Bad parsing while executing stage 2, wantErr false`

**Comment by fwessels** [comment] 2019-12-13 21:16
Duplicate of #51

**Closed as completed by fwessels** 2019-12-13 21:16 UTC
