### ISSUE TITLE
_parse_string: unexpected fault address 0xc00042c000

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#41] opened 2019-12-09 09:58 UTC
```
unexpected fault address 0xc00042c000
fatal error: fault
[signal 0xc0000005 code=0x1 addr=0xc00042c000 pc=0x532a50]

goroutine 19642 [running]:
runtime.throw(0x579ac7, 0x5)
	runtime/panic.go:774 +0x79 fp=0xc000049df0 sp=0xc000049dc0 pc=0x42e299
runtime.sigpanic()
	runtime/signal_windows.go:236 +0x228 fp=0xc000049e20 sp=0xc000049df0 pc=0x43eab8
github.com/fwessels/simdjson-go._parse_string(0x2350400, 0xc00040e604, 0xc000049e40)
	github.com/fwessels/simdjson-go/parse_string_amd64.s:231 +0x260 fp=0xc000049e28 sp=0xc000049e20 pc=0x532a50
github.com/fwessels/simdjson-go.parse_string_simd(0x23503ff, 0x2, 0x2, 0xc0001d4018, 0x1500)
	c:/gopath/src/github.com/fwessels/simdjson-go/parse_string_amd64.go:22 +0x88 fp=0xc000049e60 sp=0xc000049e28 pc=0x5289d8
github.com/fwessels/simdjson-go.parse_string(0x2350000, 0x401, 0x401, 0xc0001d4000, 0x3f2, 0x3ff, 0x200)
	c:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:31 +0xdd fp=0xc000049eb8 sp=0xc000049e60 pc=0x52e64d
github.com/fwessels/simdjson-go.unified_machine(0x2350000, 0x401, 0x401, 0xc0001d4000, 0x0)
	c:/gopath/src/github.com/fwessels/simdjson-go/stage2_build_tape.go:282 +0xe9b fp=0xc000049f78 sp=0xc000049eb8 pc=0x53007b
github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage.func2(0x2350000, 0x401, 0x401, 0xc0001d4000, 0xc000044330, 0xc000012370)
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:107 +0x6c fp=0xc000049fb0 sp=0xc000049f78 pc=0x53201c
runtime.goexit()
	runtime/asm_amd64.s:1357 +0x1 fp=0xc000049fb8 sp=0xc000049fb0 pc=0x455ce1
created by github.com/fwessels/simdjson-go.(*internalParsedJson).parseMessage
	c:/gopath/src/github.com/fwessels/simdjson-go/parsed_json.go:106 +0x1a2

goroutine 1 [semacquire]:
fatal error: unexpected signal during runtime execution
panic during panic
[signal 0xc0000005 code=0x0 addr=0xe8 pc=0x44ae94]

runtime stack:
runtime.throw(0x582460, 0x2a)
	runtime/panic.go:774 +0x79
runtime.sigpanic()
	runtime/signal_windows.go:227 +0x25a
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000038000, 0x0, 0x0, 0x64, 0x0, 0x0, 0x0, ...)
	runtime/traceback.go:261 +0x1314
runtime.traceback1(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000038000, 0x0)
	runtime/traceback.go:722 +0xf7
runtime.traceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000038000)
	runtime/traceback.go:676 +0x59
runtime.tracebackothers(0xc000039080)
	runtime/traceback.go:929 +0x1bb
runtime.dopanic_m(0xc000039080, 0x42e299, 0xc000049dc0, 0x579ac7)
	runtime/panic.go:974 +0x18f
runtime.fatalthrow.func1()
	runtime/panic.go:829 +0x6a
runtime.systemstack(0x0)
	runtime/asm_amd64.s:370 +0x6b
runtime.mstart()
	runtime/proc.go:1146
exit status 2
```

Related to #33?

Repro: [f058d9ce0c451c0da6f8f14745f3312258b64bac.gz](https://github.com/fwessels/simdjson-go/files/3938998/f058d9ce0c451c0da6f8f14745f3312258b64bac.gz)

**Comment by fwessels** [comment] 2019-12-09 20:45
Yes, duplicate of #33

**Closed as completed by fwessels** 2019-12-09 20:45 UTC
