### ISSUE TITLE
Newline at end

### ISSUE THREAD

**Issue by klauspost** [fwessels/simdjson-go#50] opened 2019-12-12 09:31 UTC
```
		{
			name: "newline-at-end",
			js: `{"00":null,"0":null}
`,
			want:    `{"00":null,"0":null}`,
			wantErr: false,
		},
```

got: `error = Bad parsing while executing stage 2, wantErr false`

**Comment by fwessels** [comment] 2019-12-13 21:29
Duplicate of #51 (`null` parsing at end failed)

**Closed as completed by fwessels** 2019-12-13 21:29 UTC
